import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
// Import the Vite SSR bundle (pre-compiled) — not the TypeScript source —
// so Vite's commonjs plugin has already resolved CJS/ESM interop issues
// that would fail Node.js 22's strict ESM static linker.
import { render } from './dist/server/entry-server.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const distDir = path.join(__dirname, 'dist');

// Read the Vite-built HTML shell as the template for every page
const template = fs.readFileSync(path.join(distDir, 'index.html'), 'utf-8');

// Use the sitemap generated by the build to drive the route list
const sitemapPath = path.join(distDir, 'sitemap.xml');
const sitemapXml = fs.readFileSync(sitemapPath, 'utf-8');
const routeMatches = [...sitemapXml.matchAll(/<loc>https?:\/\/[^/]+(\/[^<]*)<\/loc>/g)];
const routes: string[] = routeMatches.map(m => m[1]).filter(Boolean);
if (!routes.includes('/')) routes.unshift('/');

let ok = 0;
let fail = 0;

for (const route of routes) {
  try {
    const { html, helmet } = render(route);

    let finalHtml = template;

    // Inject rendered React HTML into the root div
    finalHtml = finalHtml.replace(
      '<div id="root"></div>',
      `<div id="root">${html}</div>`
    );

    // Replace generic <title> with page-specific one from Helmet
    if (helmet?.title) {
      finalHtml = finalHtml.replace(/<title>[^<]*<\/title>/, helmet.title.toString());
    }

    // Remove generic meta description (Helmet will supply the page-specific one)
    finalHtml = finalHtml.replace(/<meta\s+name="description"[^>]*>\n?/, '');

    // Inject all Helmet head content (meta, link, script/JSON-LD) before </head>
    if (helmet) {
      const headContent = [
        helmet.meta?.toString() ?? '',
        helmet.link?.toString() ?? '',
        helmet.script?.toString() ?? '',
      ].filter(s => s.trim()).join('\n    ');
      if (headContent) {
        finalHtml = finalHtml.replace('</head>', `    ${headContent}\n  </head>`);
      }
    }

    // Determine output path: /devops/maturity → dist/devops/maturity/index.html
    const outputPath =
      route === '/'
        ? path.join(distDir, 'index.html')
        : path.join(distDir, ...route.replace(/^\//, '').split('/'), 'index.html');

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, finalHtml, 'utf-8');
    console.log(`  ✓  ${route}`);
    ok++;
  } catch (err) {
    console.error(`  ✗  ${route}: ${(err as Error).message}`);
    fail++;
  }
}

console.log(`\nPre-rendering complete: ${ok} succeeded, ${fail} failed out of ${routes.length} routes.\n`);
if (fail > 0) process.exit(1);
